### ISSUE TITLE
Resolve Apple Clang Pipeline Build Warnings

### ISSUE THREAD

**Issue by webberlh** [OmicsDataAutomation/OmicsDS#17]
There are two warnings triggered in the clang build process by OmicsDS code that should be resolved.

1. There is an `Wunused-comparison` in the `equivalent_schama` function of the `omicsds_loader.cc` file.
2. There is an `Wtautological-constant-out-of-range-compare` in the `OmicsExporter::query` function of the `omicsds_export.cc` file.

**Comment by nalinigans** [comment]
I think this is mostly fixed, don't see any warnings while compiling, closing for now.
